In [21]:
import numpy as np

In [1]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [7]:
tns

tensor([[ 0.5054, -0.0903, -1.6397,  1.4612,  0.7171, -1.5972, -0.0174, -0.5788,
         -0.4829, -0.3247,  1.3992, -0.2161],
        [-0.0883, -2.4292, -0.3681,  1.3289, -1.0548,  0.0404,  1.0962,  0.0097,
          0.1395,  0.5501,  2.0779,  0.0833],
        [ 0.0821,  0.6661,  0.2457, -0.9411,  0.8894, -0.1852,  0.9616,  0.1712,
          0.1258, -0.1259, -0.5063, -0.6121],
        [ 0.3497, -0.4816, -0.2097, -0.9026,  0.6483,  0.0985, -1.6840,  0.2702,
          2.9082,  0.4139,  0.6681, -0.9420],
        [-1.3374, -0.1425,  0.5030,  0.3526, -0.8167,  0.6037,  1.3774,  1.2284,
         -0.8171, -0.2630, -0.5928, -0.8559],
        [-0.9705,  2.4552, -0.9398,  0.1904,  0.2055,  1.2094,  0.7297, -0.7817,
         -1.3458, -0.0130, -2.3838, -0.3625],
        [-2.1463, -0.4915, -0.0784, -1.4347,  2.1112, -0.0513,  2.1531, -0.0551,
          1.3026,  0.9734, -1.2697,  1.1284],
        [ 0.5370, -2.4023,  1.4881,  1.2848, -0.6282, -0.5983,  0.4471, -1.0889,
         -1.2095, -0.2134, -0.

In [8]:
tns1

tensor([[ 0.5054, -0.0903, -1.6397,  1.4612],
        [-0.0883, -2.4292, -0.3681,  1.3289],
        [ 0.0821,  0.6661,  0.2457, -0.9411],
        [ 0.3497, -0.4816, -0.2097, -0.9026],
        [-1.3374, -0.1425,  0.5030,  0.3526]])

In [9]:
tns

tensor([[ 0.5054, -0.0903, -1.6397,  1.4612,  0.7171, -1.5972, -0.0174, -0.5788,
         -0.4829, -0.3247,  1.3992, -0.2161],
        [-0.0883, -2.4292, -0.3681,  1.3289, -1.0548,  0.0404,  1.0962,  0.0097,
          0.1395,  0.5501,  2.0779,  0.0833],
        [ 0.0821,  0.6661,  0.2457, -0.9411,  0.8894, -0.1852,  0.9616,  0.1712,
          0.1258, -0.1259, -0.5063, -0.6121],
        [ 0.3497, -0.4816, -0.2097, -0.9026,  0.6483,  0.0985, -1.6840,  0.2702,
          2.9082,  0.4139,  0.6681, -0.9420],
        [-1.3374, -0.1425,  0.5030,  0.3526, -0.8167,  0.6037,  1.3774,  1.2284,
         -0.8171, -0.2630, -0.5928, -0.8559],
        [-0.9705,  2.4552, -0.9398,  0.1904,  0.2055,  1.2094,  0.7297, -0.7817,
         -1.3458, -0.0130, -2.3838, -0.3625],
        [-2.1463, -0.4915, -0.0784, -1.4347,  2.1112, -0.0513,  2.1531, -0.0551,
          1.3026,  0.9734, -1.2697,  1.1284],
        [ 0.5370, -2.4023,  1.4881,  1.2848, -0.6282, -0.5983,  0.4471, -1.0889,
         -1.2095, -0.2134, -0.

In [10]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[-2.4069,  1.0016, -0.4182],
        [-3.1116,  1.2655,  1.3272]])

In [11]:
print(mat1)
print('')
print(mat2)


tensor([[ 1.9057, -1.2870, -1.7865],
        [ 1.8058, -0.9258,  1.4815]])

tensor([[-1.5878, -0.3314, -0.1525],
        [-0.1349, -1.6147, -0.7510],
        [-0.2492,  0.2491,  0.6124]])


In [24]:
import numpy as np 
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
print("Matrix p :") 
print(p) 
print("Matrix q :") 
print(q) 
result = np.dot(p, q) 
print("The matrix multiplication is :") 
print(result) 

Matrix p :
[[1, 2], [2, 3]]
Matrix q :
[[4, 5], [6, 7]]
The matrix multiplication is :
[[16 19]
 [26 31]]


In [31]:
result

array([[16, 19],
       [26, 31]])

In [32]:
c1 = [[1, 3], [5, 4]]
c3 = [[0, 1], [3, 2]]

np.dot(c1, c3)

array([[ 9,  7],
       [12, 13]])

In [30]:
c1 = [[1, 2], [4, 5]]
c3 = [[4, 5], [7, 8]]

# 1  2        4  5
# 4  5        7  8

np.dot(c1, c3)

array([[18, 21],
       [51, 60]])

In [33]:
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]

np.dot(A, B)

array([[16, 19],
       [26, 31]])

In [ ]:
1 2
2 3

4 6
5 7

In [49]:
lista_c1 = [[1,2,3], 
            [4,5,6]]

lista_c2 = [[10,20,30],
            [40,50,60],
            [70,80,30]]


In [36]:
lista_c1 = [[1,2], 
            [4,5]]

lista_c2 = [[10,20],
            [40,50]]
np.dot(lista_c1, lista_c2)

array([[ 90, 120],
       [240, 330]])

In [50]:
tns_c1 = torch.Tensor(lista_c1)
tns_c2 = torch.Tensor(lista_c2)

tns_c_mm = torch.mm(tns_c1, tns_c2)

print('size t1: {}'.format(tns_c1.size()))
print(tns_c1)
print('')
print('size t2: {}'.format(tns_c2.size()))
print(tns_c2)
print('')
print('size t mm: {}'.format(tns_c_mm.size()))
print(tns_c_mm)
print('')

size t1: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])

size t2: torch.Size([3, 3])
tensor([[10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 30.]])

size t mm: torch.Size([2, 3])
tensor([[300., 360., 240.],
        [660., 810., 600.]])



In [51]:
## Resumo do código
import torch 
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2

In [53]:
tns1

tensor([[ 4.8601e-01],
        [ 4.8932e-01],
        [ 1.7706e+00],
        [-9.7993e-01],
        [ 1.5887e-01],
        [ 1.6282e+00],
        [-9.6133e-01],
        [ 1.5081e+00],
        [-2.5623e-01],
        [ 8.9370e-01],
        [ 2.6330e-01],
        [ 1.3022e+00],
        [-9.8778e-01],
        [ 1.3283e-01],
        [-3.3429e-01],
        [-5.4582e-01],
        [-1.0916e-02],
        [ 4.9876e-02],
        [-4.7066e-01],
        [-9.2942e-01],
        [ 3.5842e-01],
        [ 4.0836e-01],
        [-7.0030e-01],
        [ 6.8051e-01],
        [-6.6264e-01],
        [-7.1055e-01],
        [-8.4822e-01],
        [-1.0626e+00],
        [ 8.0820e-01],
        [ 2.8244e-01],
        [ 2.6721e-01],
        [ 4.9068e-02],
        [-1.1716e-01],
        [ 1.6276e+00],
        [ 3.0427e-01],
        [ 1.3383e+00],
        [-1.6311e+00],
        [ 2.4603e-01],
        [-3.2737e-01],
        [ 4.9027e-01],
        [ 4.7069e-01],
        [ 4.6941e-01],
        [-1.4186e-02],
        [ 2

In [52]:
soma

tensor([[-9.2062e-02],
        [ 3.2918e+00],
        [ 2.1894e+00],
        [-2.1958e+00],
        [ 2.9801e-01],
        [ 1.6369e+00],
        [ 1.2447e+00],
        [ 1.8571e+00],
        [-1.7043e-01],
        [ 1.2735e+00],
        [ 5.2177e-01],
        [ 2.5765e+00],
        [ 2.4397e-01],
        [ 1.1260e+00],
        [-3.3045e-01],
        [-7.1581e-01],
        [-9.3036e-01],
        [-7.2574e-01],
        [-8.1318e-01],
        [-3.3869e-01],
        [ 1.3878e+00],
        [ 3.4098e-01],
        [-4.5332e-01],
        [ 1.8481e+00],
        [ 5.5487e-01],
        [-1.4375e+00],
        [-5.5456e-02],
        [-3.1618e+00],
        [ 1.4923e+00],
        [-1.8249e+00],
        [ 1.3498e+00],
        [-5.4771e-01],
        [-3.6406e-01],
        [ 2.3339e+00],
        [ 3.6219e-01],
        [-1.4068e+00],
        [-6.9058e-01],
        [-1.2065e+00],
        [-1.5637e+00],
        [ 3.6235e+00],
        [ 9.3670e-01],
        [ 4.1418e-01],
        [ 1.0427e+00],
        [ 4

In [54]:
c1 = [[1, 3], [5, 4]]
c3 = [[0, 1], [3, 2]]

np.dot(c1, c3)

array([[ 9,  7],
       [12, 13]])

In [58]:
for i, v1 in enumerate(c1):
    
    print(i)

    print(v1)

0
[1, 3]
1
[5, 4]


In [60]:
v1[0]

5